
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 15 21:07:02 EDT 2011
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 6;
  public static final int GTEQ = 14;
  public static final int LBRACKET = 24;
  public static final int UMINUS = 21;
  public static final int SMALLER = 11;
  public static final int LPAREN = 22;
  public static final int GREATER = 12;
  public static final int SEMI = 2;
  public static final int FOR = 33;
  public static final int MINUS = 4;
  public static final int RPAREN = 23;
  public static final int NOT = 20;
  public static final int AND = 18;
  public static final int OR = 19;
  public static final int COMMA = 10;
  public static final int CLASS = 37;
  public static final int PBRACKET = 26;
  public static final int TBOOL = 30;
  public static final int DOTDOT = 9;
  public static final int PLUS = 3;
  public static final int ASSIGN = 17;
  public static final int IF = 34;
  public static final int ID = 42;
  public static final int DOT = 8;
  public static final int EOF = 0;
  public static final int RETURN = 40;
  public static final int RBRACKET = 25;
  public static final int NEW = 39;
  public static final int error = 1;
  public static final int SELF = 35;
  public static final int NUMBER = 41;
  public static final int MOD = 7;
  public static final int NEQ = 16;
  public static final int TVOID = 31;
  public static final int TIMES = 5;
  public static final int TINT = 29;
  public static final int ELSE = 36;
  public static final int LBRACE = 27;
  public static final int WHILE = 32;
  public static final int EQL = 15;
  public static final int SMEQ = 13;
  public static final int RBRACE = 28;
  public static final int EXTENDS = 38;
}

